steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.1.1:
        files: hooks/**

  - label: ":sparkles:"
    plugins:
      plugin-linter#v1.0.0:
        name: docker

  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v1.3.1:
        run: tests
